name: Publish

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true

      - name: Make Gradle executable
        # language=bash
        run: chmod +x ./gradlew

      - name: Setup Java 8
        # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#java
        # language=bash
        run: ::set-env name=JAVA_HOME::$(echo $JAVA_HOME_8_X64)

      - name: Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
